all:    
	mkdir bin
	cp src/sym_table.py bin/sym_table.py
	cp src/parser.py bin/parser
	cp src/lexer.py bin/lexer.py
	cp src/codegen.py bin/codegen
	cp src/compile bin/compiler
	chmod 777 bin/*
	chmod +x bin/*
clean:
	rm -r bin/
