all:	
	mkdir bin
	cp src/parser.py bin/
	cp src/lexer.py bin/
	cp src/html.py bin/make_html.py
	cp src/parser bin/parser
	chmod 777 bin/*
	chmod +x bin/*

clean:
	rm -r bin/
	rm for_tree.txt output.txt out.txt parser.out parser.txt parsetab.py right_derivation.html errors.txt
